apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: centralpromopet-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ltreven/centralpromopet.git
    targetRevision: main
    path: charts/centralpromopet
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: centralpromopet-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

