imagePullSecrets:
  - name: ghcr-pull-secret
api:
  googleClientId: "8433826157-dfk00obfltkj7k9ef364g78fpn3qspv3.apps.googleusercontent.com"
  adminEmails: "ltreven@gmail.com"
  appOrigins: "https://centralpromopet-stg.sabialabs.de"
  image:
    repository: ghcr.io/ltreven/centralpromopet-api
    tag: 79dfe8c1b085a6163755ab36ad70a24171fb6b52
    pullPolicy: Always
  existingSecret: centralpromopet-api-secret
web:
  image:
    repository: ghcr.io/ltreven/centralpromopet-web
    tag: 79dfe8c1b085a6163755ab36ad70a24171fb6b52
    pullPolicy: Always
postgres:
  auth:
    existingSecret: centralpromopet-db-credentials
  persistence:
    enabled: true
    size: 10Gi
    storageClass: local-path
migrations:
  enabled: true
stagingSeed:
  enabled: true
ingress:
  className: traefik
  host: centralpromopet-stg.sabialabs.de
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
    secretName: centralpromopet-staging-tls
