imagePullSecrets:
  - name: ghcr-pull-secret
api:
  appOrigins: "https://centralpromopet-stg.sabialabs.de"
  image:
    repository: ghcr.io/ltreven/centralpromopet-api
    tag: 3f16dad8b8854f5250911247112d2b46505d5d06
    pullPolicy: Always
  existingSecret: centralpromopet-api-secret
web:
  image:
    repository: ghcr.io/ltreven/centralpromopet-web
    tag: 3f16dad8b8854f5250911247112d2b46505d5d06
    pullPolicy: Always
postgres:
  auth:
    existingSecret: centralpromopet-db-credentials
  persistence:
    enabled: true
    size: 10Gi
    storageClass: local-path
migrations:
  enabled: true
stagingSeed:
  enabled: true
ingress:
  className: traefik
  host: centralpromopet-stg.sabialabs.de
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
    secretName: centralpromopet-staging-tls
