api:
  googleClientId: "8433826157-dfk00obfltkj7k9ef364g78fpn3qspv3.apps.googleusercontent.com"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "2"
      memory: 1Gi

web:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi
